common:
  retry_attempts: 3
  retry_backoff: 0.5
  timeout: 15.0
  web_paths:
    forgot_password: /forgot-password
    help: /help
    privacy: /privacy
    register: /register
    terms: /terms
default: development
development:
  api_base_url: http://127.0.0.1:8000/api
  web_base_url: http://127.0.0.1:3000
production:
  api_base_url: http://123.57.206.182:8000/api
  web_base_url: http://www.example.com
staging:
  api_base_url: http://staging-api.example.com/api
  web_base_url: http://staging.example.com
testing:
  api_base_url: http://test-api.example.com/api
  web_base_url: http://test.example.com
