name: Build and Release

on:
  push:
    branches:
      - 'build/**'
      - 'feat/**'
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: '3.11'
            artifact_name: windows
          - os: macos-latest
            python-version: '3.11'
            artifact_name: macos

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --frozen

    - name: Create necessary directories
      run: mkdir -p models result logs
      shell: bash

    - name: Initialize database
      run: uv run python -c "import orm.inint"
      shell: bash

    - name: Install Inno Setup (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install innosetup -y
      shell: bash

    - name: Build with PyInstaller
      run: uv run python install_build.py
      shell: bash
      env:
        PYTHONIOENCODING: utf-8

    - name: List dist directory (debug)
      run: |
        echo "=== Contents of dist/ ==="
        ls -lah dist/
      shell: bash

    - name: Upload artifacts (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: Lapped-${{ matrix.artifact_name }}
        path: dist/*.exe
        if-no-files-found: error

    - name: Upload artifacts (macOS)
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: Lapped-${{ matrix.artifact_name }}
        path: dist/*.dmg
        if-no-files-found: error

    - name: Create Release (Windows)
      if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'Windows'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release (macOS)
      if: startsWith(github.ref, 'refs/tags/v') && runner.os == 'macOS'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
